# Generated by Django 4.2.3 on 2023-07-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='to_do',
            field=models.BooleanField(default=False),
        ),
    ]
